SKT fix mean longitude of perihelion calc for static orbits in radfor.F
derpycode/cgenie.muffin pull request #140
Opened 2020-09-09 15:15 UTC by kirtlandster

2020-09-16 18:55 UTC, pamverv001 requested changes
Ran two simulations, one with orbital parameters specified via parameters (osce, oscsob, oscgam), one with orbital parameters specified in orbital forcing file ('alternative configuation'). Used La2004 at 10 ka. 

> ea_par_orbit_osce=0.01943
> ea_par_orbit_oscsob=0.41042
> ea_par_orbit_oscgam=295.2665 

and

> 10    0.01943    0.41042    4.28902  194.15793 (in file)

biogem_series_misc_ocn_insol.res is **not** the same!

2020-09-16 19:56 UTC, kirtlandster commented
The time varying can’t exactly be compared to static orbits because of tau.

Sandra Kirtland Turner, PhD
Associate Professor of Paleoclimate/Paleoceanography 
Department of Earth Sciences
University of California, Riverside


> On Sep 16, 2020, at 12:00, Pam Vervoort <notifications@github.com> wrote:
> 
> ﻿
> @pamverv001 requested changes on this pull request.
> 
> Ran two simulations, one with orbital parameters specified via parameters (osce, oscsob, oscgam), one with orbital parameters specified in orbital forcing file ('alternative configuation'). Used La2004 at 10 ka.
> 
> ea_par_orbit_osce=0.01943
> ea_par_orbit_oscsob=0.41042
> ea_par_orbit_oscgam=295.2665
> 
> and
> 
> 10 0.01943 0.41042 4.28902 194.15793 (in file)
> 
> biogem_series_misc_ocn_insol.res is not the same!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-17 17:57 UTC, pamverv001 commented
Ran a simulation with transient orbital forcing for 5000 years. Insolation output (misc_ocn_insol.res) and environmental variables (CO2, DIC) are exactly the same as the same simulation performed in the master branch

2020-09-17 17:58 UTC, pamverv001 approved these changes

2020-09-17 18:12 UTC, merged